spring:
  data:
    elasticsearch:
      cluster-name: my-application
      cluster-nodes: 127.0.0.1:9300
    mongodb:
      uri: mongodb://localhost:27017/testdb
  application:
    name: athena-client
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: 11c1bf0e-8a0f-4aef-98b0-2a914a0f02aa
        cluster-name: NJ
server:
  port: 8088